# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

service:
  type: LoadBalancer
  port: 9999
  targetPort: 8080
  protocol: TCP

resources:
  limits:
    cpu: '1'
    memory: 900Mi
  requests:
    cpu: '0.5'
    memory: 450Mi